import sys
import os

seqs = {
    "O00299": [
        "MAEEQPQVELFVKAGSDGAKIGNCPFSQRLFMVLWLKGVTFNVTTVDTKRRTETVQKLCPGGQLPFLLYGTEVHTDTNKIEEFLEAVLCPPRYPKLAALNPESNTAGLDIFAKFSAYIKNSNPALNDNLEKGLLKALKVLDNYLTSPLPEEVDETSAEDEGVSQRKFLDGNELTLADCNLLPKLHIVQVVCKKYRGFTIPEAFRGVHRYLSNAYAREEFASTCPDDEEIELAYEQVAKALK"
    ],
    "O16305": [
        "MADQLTEEQIAEFKEAFSLFDKDGDGTITTKELGTVMRSLGQNPTEAELQDMINEVDADGNGTIDFPEFLTMMARKMKDTDSEEEIREAFRVFDKDGNGFISAAELRHVMTNLGEKLTDEEVDEMIREADIDGDGQVNYEEFVTMMTTK"
    ],
    "O31408": [
        "MNKGQRHIKIREIIMSNDIETQDELVDRLREAGFNVTQATVSRDIKEMQLVKVPMANGRYKYSLPSDQRFNPLQKLKRALVDVFIKLDGTGNLLVLRTLPGNAHAIGVLLDNLDWDEIVGTICGDDTCLIICRTPKDAKKVSNQLLSML"
    ],
    "O44342": [
        "AVTCTGCVDLDELSFEKTVERFPYSVVKFDIAYPYGEKHEAFTAFSKSAHKATKDLLIATVGVKDYGELENKALGDRYKVDDKNFPSIFLFKGNADEYVQLPSHVDVTLDNLKAFVSANTPLYIGRDGCIKEFNEVLKNYANIPDAEQLKLIEKLQAKQEQLTDPEQQQNARAYLIYMRKIHEVGYDFLEEETKRLLRLKAGKVTEAKKEELLRKLNILEVFRVHKVTKTAPEKEEL"
    ],
    "O75554": [
        "DPSKGRWVEGITSEGYHYYYDLISGASQWEKPEGFQGDLKKTAVKTVWVEGLSEDGFTYYYNTETGESRWEKPDD"
    ],
    "P00698": [
        "MRSLLILVLCFLPLAALGKVFGRCELAAAMKRHGLDNYRGYSLGNWVCAAKFESNFNTQATNRNTDGSTDYGILQINSRWWCNDGRTPGSRNLCNIPCSALLSSDITASVNCAKKIVSDGNGMNAWVA"
    ],
    "P02526": [
        "MGKITFYEDRGFQGHCYECSSDCPNLQPYFSRCNSIRVDSGCWMLYERPNYQGHQYFLRRGDYPDYQQWMGFNDSIRSCRLIPQHTGTFRMRIYERDDFRGQMSEITDDCPSLQDRFHLTEVHSLNVLEGSWVLYEMPSYRGRQYLLRPGEYRRYLDWGAMNAKVGSLRRVMDFY"
    ],
    "P02829": [
        "MASETFEFQAEITQLMSLIINTVYSNKEIFLRELISNASDALDKIRYKSLSDPKQLETEPDLFIRITPKPEQKVLEIRDSGIGMTKAELINNLGTIAKSGTKAFMEALSAGADVSMIGQFGVGFYSLFLVADRVQVISKSNDDEQYIWESNAGGSFTVTLDEVNERIGRGTILRLFLKDDQLEYLEEKRIKEVIKRHSEFVAYPIQLVVTKEVEKEVPIPEEEKKDEEKKDEEKKDEDDKKPKLEEVDEEEEKKPKTKKVKEEVQEIEELNKTKPLWTRNPSDITQEEYNAFYKSISNDWEDPLYVKHFSVEGQLEFRAILFIPKRAPFDLFESKKKKNNIKLYVRRVFITDEAEDLIPEWLSFVKGVVDSEDLPLNLSREMLQQNKIMKVIRKNIVKKLIEAFNEIAEDSEQFEKFYSAFSKNIKLGVHEDTQNRAALAKLLRYNSTKSVDELTSLTDYVTRMPEHQKNIYYITGESLKAVEKSPFLDALKAKNFEVLFLTDPIDEYAFTQLKEFEGKTLVDI"
    ],
    "P06616": [
        "MSIDKSYCGFIAIVGRPNVGKSTLLNKLLGQKISITSRKAQTTRHRIVGIHTEGAYQAIYVDTPGLHMEEKRAINRLMNKAASSSIGDVELVIFVVEGTRWTPDDEMVLNKLREGKAPVILAVNKVDNVQEKADLLPHLQFLASQMNFLDIVPISAETGLNVDTIAAIVRKHLPEATHHFPEDYITDRSQRFMASEIIREKLMRFLGAELPYSVTVEIERFVSNERGGYDINGLILVEREGQKKMVIGNKGAKIKTIGIEARKDMQEMFEAPVHLELWVKVKSGWADDERALRSLGYVDDL"
    ],
    "P06766": [
        "MSKRKAPQETLNGGITDMLVELANFEKNVSQAIHKYNAYRKAASVIAKYPHKIKSGAEAKKLPGVGTKIAEKIDEFLATGKLRKLEKIRQDDTSSSINFLTRVTGIGPSAARKLVDEGIKTLEDLRKNEDKLNHHQRIGLKYFEDFEKRIPREEMLQMQDIVLNEVKKLDPEYIATVCGSFRRGAESSGDMDVLLTHPNFTSESSKQPKLLHRVVEQLQKVRFITDTLSKGETKFMGVCQLPSENDENEYPHRRIDIRLIPKDQYYCGVLYFTGSDIFNKNMRAHALEKGFTINEYTIRPLGVTGVAGEPLPVDSEQDIFDYIQWRYREPKDRSE"
    ],
    "P0A6I9": [
        "MRYIVALTGGIGSGKSTVANAFADLGINVIDADIIARQVVEPGAPALHAIADHFGANMIAADGTLQRRALRERIFANPEEKNWLNALLHPLIQQETQHQIQQATSPYVLWVVPLLVENSLYKKANRVLVVDVSPETQLKRTMQRDDVTREHVEQILAAQATREARLAVADDVIDNNGAPDAIASDVARLHAHYLQLASQFVSQEKP"
    ],
    "P0AEN1": [
        "MTTLSCKVTSVEAITDTVYRVRIVPDAAFSFRAGQYLMVVMDERDKRPFSMASTPDEKGFIELHIGASEINLYAKAVMDRILKDHQIVVDIPHGEAWLRDDEERPMILIAGGTGFSYARSILLTALARNPNRDITIYWGGREEQHLYDLCELEALSLKHPGLQVVPVVEQPEAGWRGRTGTVLTAVLQDHGTLAEHDIYIAGRFEMAKIARDLFCSERNAREDRLFGDAFAFI"
    ],
    "P0AFU8": [
        "MFTGIVQGTAKLVSIDEKPNFRTHVVELPDHMLDGLETGASVAHNGCCLTVTEINGNHVSFDLMKETLRITNLGDLKVGDWVNVERAAKFSDEIGGHLMSGHIMTTAEVAKILTSENNRQIWFKVQDSQLMKYILYKGFIGIDGISLTVGEVTPTRFCVHLIPETLERTTLGKKKLGARVNIEIDPQTQAVVDTVERVLAARENAMNQPGTEA"
    ],
    "P0CG48_1": [
        "MQIFVKTLTGKTITLEVEPSDTIENVKAKIQDKEGIPPDQQRLIFAGKQLEDGRTLSDYNIQKESTLHLVLRLRGG"
    ],
    "P0CG48_2": [
        "MQIFVKTLTGKTITLEVEPSDTIENVKAKIQDKEGIPPDQQRLIFAGKQLEDGRTLSDYNIQKESTLHLVLRLRGGMQIFVKTLTGKTITLEVEPSDTIENVKAKIQDKEGIPPDQQRLIFAGKQLEDGRTLSDYNIQKESTLHLVLRLRGG"
    ],
    "P13988": [
        "MAKANSSFSEVQIARRIKEGRGQGHGKDYIPWLTVQEVPSSGRSHRIYSHKTGRVHHLLSDLELAVFLSLEWESSVLDIREQFPLLPSDTRQIAIDSGIKHPVIRGVDQVMSTDFLVDCKDGPFEQFAIQVKPAAALQDERTLEKLELERRYWQQKQIPWFIFTDKEINPVVKENIEWLYSVKTEEVSAELLAQLSPLAHILQEKGDENIINVCKQVDIAYDLELGKTLSEIRALTANGFIKFNIYKSFRANKCADLCISQVVNMEELRYVAN"
    ],
    "P17291": [
        "MARRRRAEVRQLQPDLVYGDVLVTAFINKIMRDGKKNLAARIFYDACKIIQEKTGQEPLKVFKQAVENVKPRMEVRSRRVGGANYQVPMEVSPRRQQSLALRWLVQAANQRPERRAAVRIAHELMDAAEGKGGAVKKKEDVERMAEANRAYAHYRW"
    ],
    "P19157": [
        "MPPYTIVYFPVRGRCEAMRMLLADQGQSWKEEVVTIDTWMQGLLKPTCLYGQLPKFEDGDLTLYQSNAILRHLGRSLGLYGKNQREAAQMDMVNDGVEDLRGKYVTLIYTNYENGKNDYVKALPGHLKPFETLLSQNQGGKAFIVGDQISFADYNLLDLLLIHQVLAPGCLDNFPLLSAYVARLSARPKIKAFLSSPEHVNRPINGNGKQ"
    ],
    "P24941": [
        "MENFQKVEKIGEGTYGVVYKARNKLTGEVVALKKIRLDTETEGVPSTAIREISLLKELNHPNIVKLLDVIHTENKLYLVFEFLHQDLKKFMDASALTGIPLPLIKSYLFQLLQGLAFCHSHRVLHRDLKPQNLLINTEGAIKLADFGLARAFGVPVRTYTHEVVTLWYRAPEILLGCKYYSTAVDIWSLGCIFAEMVTRRALFPGDSEIDQLFRIFRTLGTPDEVVWPGVTSMPDYKPSFPKWARQDFSKVVPPLDEDGRSLLSQMLHYDPNKRISAKAALAHPFFQDVTKPVPHLRL"
    ],
    "P30626": [
        "MAYPGHPGAGGGYYPGGYGGAPGGPAFPGQTQDPLYGYFAAVAGQDGQIDADELQRCLTQSGIAGGYKPFNLETCRLMVSMLDRDMSGTMGFNEFKELWAVLNGWRQHFISFDTDRSGTVDPQELQKALTTMGFRLSPQAVNSIAKRYSTNGKITFDDYIACCVKLRALTDSFRRRDTAQQGVVNFPYDDFIQCVMSV"
    ],
    "P31946": [
        "MTMDKSELVQKAKLAEQAERYDDMAAAMKAVTEQGHELSNEERNLLSVAYKNVVGARRSSWRVISSIEQKTERNEKKQQMGKEYREKIEAELQDICNDVLELLDKYLIPNATQPESKVFYLKMKGDYFRYLSEVASGDNKQTTVSNSQQAYQEAFEISKKEMQPTHPIRLGLALNFSVFYYEILNSPEKACSLAKTAFDEAIAELDTLNEESYKDSTLIMQLLRDNLTLWTSENQGDEGDAGEGEN"
    ],
    "P42212": [
        "MSKGEELFTGVVPILVELDGDVNGHKFSVSGEGEGDATYGKLTLKFICTTGKLPVPWPTLVTTFSYGVQCFSRYPDHMKQHDFFKSAMPEGYVQERTIFFKDDGNYKTRAEVKFEGDTLVNRIELKGIDFKEDGNILGHKLEYNYNSHNVYIMADKQKNGIKVNFKIRHNIEDGSVQLADHYQQNTPIGDGPVLLPDNHYLSTQSALSKDPNEKRDHMVLLEFVTAAGITHGMDELYK"
    ],
    "P43626": [
        "HEGVHRKPSLLAHPGRLVKSEETVILQCWSDVMFEHFLLHREGMFNDTLRLIGEHHDGVSKANFSISRMTQDLAGTYRCYGSVTHSPYQVSAPSDPLDIVIIGLYEKPSLSAQLGPTVLAGENVTLSCSSRSSYDMYHLSREGEAHERRLPAGPKVNGTFQADFPLGPATHGGTYRCFGSFHDSPYEWSKSSDPLLVSVT"
    ],
    "P43895": [
        "MSQMELIKKLREATGAGMMDVKRALEDAGWDEEKAVQLLRERGAMKAAKKADREAREGIIGHYIHHNQRVGVLVELNCETDFVARNELFQNLAKDLAMHIAMMNPRYVSAEEIPAEELEKERQIYIQAALNEGKPQQIAEKIAEGRLKKYLEEVVLLEQPFVKDDKVKVKELIQQAIAKIGENIVVRRFCRFELGA"
    ],
    "Q13469": [
        "WPLSSQSGSYELRIEVQPKPHHRAHYETEGSRGAVKAPTGGHPVVQLHGYMENKPLGLQIFIGTADERILKPHAFYQVHRITGKTVTTTSYEKIVGNTKVLEIPLEPKNNMRATIDCAGILKLRNADIELRKGETDIGRKNTRVRLVFRVHIPESSGRIVSLQTASNPIECSQRSAHELPMVERQDTDSCLVYGGQQMILTGQNFTSESKVVFTEKTTDGQQIWEMEATVDKDKSQPNMLFVEIPEYRNKHIRTPVKVNFYVINGKRKRSQPQHFTYHPV"
    ],
    "Q8VQD7": [
        "MAREVKLTKAGYERLMKQLEQERERLQEATKILQELMESSDDYDDSGLEAAKQEKARIEARIDSLEDVLSRAVILEEGTGEVIGLGSVVELEDPATGERLSVQVVSPAEASVLENPMKISDASPMGKALLGHRVGDVLSLDTPKGKKEFRVVAIHGR"
    ],
    "Q9HTW3": [
        "MSQSNTLTVQILDKEYCINCPDDERANLESAARYLDGKMREIRSSGKVIGADRVAVMAALNITHDLLHRKERLDQESSSTRERVRELLDRVDRALANPADAGEA"
    ],
    "Q9LDC0": [
        "NVPPKVDSEAEVLDEKVSKQIIKEGHGSKPSKYSTCFLHYRAWTKNSQHKFEDTWHEQQPIELVLGKEKKELAGLAIGVASMKSGERALVHVGWELAYGKEGNFSFPNVPPMADLLYEVEVIGFDETKEGKARSDMTVEERIGAADRRKMDGNSLFKEEKLEEAMQQYEMAIAYMGDDFMFQLYGKYQDMALAVKNPCHLNIAACLIKLKRYDEAIGHCNIVLTEEEKNPKALFRRGKAKAELGQMDSARDDFRKAQKYAPDDKAIRRELRALAEQ"
    ],
}

topdir = "/Users/diegoda/Documents/protein_folding_dda/dataset1"
for subdir in ["alphaflow_md", "alphaflow_pdb", "esmflow_md", "esmflow_pdb"]:
    prefix = "jussupow_" + subdir[0] + "flow_" + subdir.split("_")[1]
    for i, seqname in enumerate(seqs.keys(), start=1):
        oldfile = os.path.join(topdir, subdir, f"{prefix}_{i}.pdb")
        newfile = os.path.join(topdir, subdir, f"{seqname}.pdb")
        cmd = f"mv {oldfile} {newfile}"
        print(cmd)
        os.system(cmd)
